name: PR checks

on:
  pull_request:
    branches: [ main ]
    paths:
      - 'lib/**'
      - 'test/**'
      - 'mix.lock'
  workflow_dispatch:

env:
  MIX_ENV: test

jobs:
  code-quality:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version:
          - { elixir: '1.18.4-otp-28', otp: '28.0.1' }
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - uses: erlef/setup-beam@e6d7c94229049569db56a7ad5a540c051a010af9 # v1.20.4
        with:
          otp-version: ${{ matrix.version.otp }}
          elixir-version: ${{ matrix.version.elixir }}
      - uses: actions/cache@0400d5f644dc74513175e3cd8d07132dd4860809 # v4.2.4
        with:
          path: deps
          key: ${{ runner.os }}-mix-${{ hashFiles('mix.lock') }}
          restore-keys: |
            ${{ runner.os }}-mix-
      - uses: actions/cache@0400d5f644dc74513175e3cd8d07132dd4860809 # v4.2.4
        with:
          path: _build
          key: ${{ runner.os }}-build-${{ hashFiles('mix.lock') }}
          restore-keys: |
            ${{ runner.os }}-build-
      - run: mix deps.get
      - run: mix deps.compile
      - run: mix compile --no-deps-check --return-errors --warnings-as-errors
      - run: mix format --check-formatted
      - run: mix credo

  test:
    runs-on: ubuntu-latest
    needs: [code-quality]
    strategy:
      matrix:
        version:
          - { elixir: '1.14.x', otp: '24.x' }
          - { elixir: '1.14.x', otp: '25.x' }
          - { elixir: '1.15.x', otp: '25.x' }
          - { elixir: '1.15.x', otp: '26.x' }
          - { elixir: '1.16.3-otp-26', otp: '26.2.5.13' }
          - { elixir: '1.17.3-otp-26', otp: '26.2.5.13' }
          - { elixir: '1.17.3-otp-27', otp: '27.3.4.1' }
          - { elixir: '1.18.4-otp-26', otp: '26.2.5.13' }
          - { elixir: '1.18.4-otp-27', otp: '27.3.4.1' }
          - { elixir: '1.18.4-otp-28', otp: '28.0.1' }
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - uses: erlef/setup-beam@e6d7c94229049569db56a7ad5a540c051a010af9 # v1.20.4
        with:
          otp-version: ${{ matrix.version.otp }}
          elixir-version: ${{ matrix.version.elixir }}
      - uses: actions/cache@0400d5f644dc74513175e3cd8d07132dd4860809 # v4.2.4
        with:
          path: deps
          key: ${{ runner.os }}-mix-${{ hashFiles('mix.lock') }}
          restore-keys: |
            ${{ runner.os }}-mix-
      - uses: actions/cache@0400d5f644dc74513175e3cd8d07132dd4860809 # v4.2.4
        with:
          path: _build
          key: ${{ runner.os }}-build-${{ hashFiles('mix.lock') }}
          restore-keys: |
            ${{ runner.os }}-build-
      - run: mix deps.get
      - run: mix deps.compile
      - run: mix compile --no-deps-check --return-errors --warnings-as-errors
      - run: mix test
