name: Publish to Hex

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    name: Test and Publish
    runs-on: ubuntu-latest

    strategy:
      matrix:
        version:
          - { elixir: '1.18.4-otp-28', otp: '28.0.1' }
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - run: |
          tag_version=${GITHUB_REF##*/v}
          project_version=$(cat mix.exs | grep '@version ' | cut -d '"' -f2)

          echo "Tag version:      ${tag_version}"
          echo "Project version:  ${project_version}"

          if [ "$tag_version" != "$project_version" ]; then
            echo "Tag version (${tag_version}) does not match project version (${project_version})"
            exit 1
          fi
      - uses: erlef/setup-beam@e6d7c94229049569db56a7ad5a540c051a010af9 # v1.20.4
        with:
          otp-version: ${{ matrix.version.otp }}
          elixir-version: ${{ matrix.version.elixir }}
      - uses: actions/cache@0400d5f644dc74513175e3cd8d07132dd4860809 # v4.2.4
        with:
          path: deps
          key: ${{ runner.os }}-mix-${{ hashFiles('mix.lock') }}
          restore-keys: |
            ${{ runner.os }}-mix-

      - uses: actions/cache@0400d5f644dc74513175e3cd8d07132dd4860809 # v4.2.4
        with:
          path: _build
          key: ${{ runner.os }}-build-${{ hashFiles('mix.lock') }}
          restore-keys: |
            ${{ runner.os }}-build-
      - run: mix deps.get
      - run: MIX_ENV=test mix deps.compile
      - run: MIX_ENV=test mix compile --no-deps-check --return-errors --warnings-as-errors
      - run: mix test
      - run: mix credo
      - run: |
          mix hex.config api_key ${{ secrets.HEX_API_KEY }}
          mix hex.publish --yes
